"""The frozen-path gate, in two modes that guard different things.

`verify` hashes every frozen path and compares against tools/frozen.sha256. It is fast,
offline, and runs in the inner ring -- it catches a working tree that drifted.

`diff` is the one that actually holds. A hash manifest cannot defend itself: whoever edits
the frozen file can regenerate the manifest in the same commit. So CI fails ANY pull
request whose diff names a frozen path, with no override token of any kind. A frozen path
changes only by a human pushing straight to main -- which the loop cannot do, because the
loop opens pull requests and does not merge (spec section 7.10).
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from collections.abc import Sequence
from fnmatch import fnmatch
from pathlib import Path

MANIFEST = "tools/frozen.sha256"
GLOBS = "tools/frozen.txt"


def frozen_globs(root: Path) -> list[str]:
    lines = (root / GLOBS).read_text(encoding="utf-8").splitlines()
    return [ln.strip() for ln in lines if ln.strip() and not ln.lstrip().startswith("#")]


def _matches(rel: str, glob: str) -> bool:
    if glob.endswith("/**"):
        return rel.startswith(glob[:-2])
    return fnmatch(rel, glob)


def _listed(root: Path) -> list[str]:
    """Every file git considers part of the working tree: tracked, plus untracked ones
    that are not ignored.

    NOT `rglob`, and the difference is fatal rather than stylistic. A frozen glob like
    `loop/**` matches `loop/__pycache__/*.pyc`, and a .pyc embeds its source's mtime --
    so a manifest written on one machine can never verify on another, and CI would go
    red on its first run for a reason that looks exactly like tampering. `rglob` also
    walks .venv: 2,563 of this repository's 2,621 files, on every inner-ring run.

    `--others --exclude-standard` keeps untracked-but-not-ignored files in scope, so a
    freshly written acceptance test is seen before it is ever committed.
    """
    out = subprocess.run(
        ("git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"),
        cwd=root, check=True, capture_output=True, text=True,
    )
    return [rel for rel in out.stdout.split("\0") if rel]


def frozen_paths(root: Path) -> list[str]:
    globs = frozen_globs(root)
    return sorted(
        rel
        for rel in set(_listed(root))
        # A manifest cannot contain its own hash; the diff mode defends it instead.
        if rel != MANIFEST
        # `--cached` still lists a tracked file deleted from disk. Such a path is absent
        # here, and `verify` reports it through the recorded-but-missing arm.
        and (root / rel).is_file()
        and any(_matches(rel, glob) for glob in globs)
    )


def hash_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _read_manifest(root: Path) -> dict[str, str]:
    target = root / MANIFEST
    if not target.exists():
        return {}
    out: dict[str, str] = {}
    for line in target.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        digest, rel = line.split("  ", 1)
        out[rel] = digest
    return out


def write_manifest(root: Path) -> None:
    lines = [
        "# Generated by `python -m tools.freeze_check update`. Frozen; see tools/frozen.txt.",
        *(f"{hash_file(root / rel)}  {rel}" for rel in frozen_paths(root)),
    ]
    (root / MANIFEST).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def verify(root: Path) -> list[str]:
    recorded = _read_manifest(root)
    present = frozen_paths(root)
    drifted = {rel for rel in present if recorded.get(rel) != hash_file(root / rel)}
    drifted |= {rel for rel in recorded if rel not in present}
    return sorted(drifted)


def offending_paths(root: Path, changed: Sequence[str]) -> list[str]:
    globs = frozen_globs(root)
    return sorted({rel for rel in changed if rel and any(_matches(rel, g) for g in globs)})


def _changed_since(base: str, root: Path) -> list[str]:
    out = subprocess.run(
        ("git", "diff", "--name-only", f"{base}...HEAD"),
        # cwd=root, not the process's working directory: without it `--root` is a lie,
        # and the mode silently reports on whatever repository the caller happens to be
        # standing in. CI runs from the repo root, so the bug would never have surfaced
        # there -- which is exactly why it is worth closing now.
        cwd=root, check=True, capture_output=True, text=True,
    )
    return [line.strip() for line in out.stdout.splitlines() if line.strip()]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("verify", "update", "diff"))
    parser.add_argument("--base", default="origin/main")
    parser.add_argument("--root", default=".")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    if args.mode == "update":
        write_manifest(root)
        print(f"wrote {MANIFEST} for {len(frozen_paths(root))} frozen paths")
        return 0

    if args.mode == "verify":
        drifted = verify(root)
        if drifted:
            print("FROZEN PATHS DRIFTED:", file=sys.stderr)
            for rel in drifted:
                print(f"  {rel}", file=sys.stderr)
            return 1
        print(f"{len(frozen_paths(root))} frozen paths verified")
        return 0

    offending = offending_paths(root, _changed_since(args.base, root))
    if offending:
        print(
            "This pull request changes frozen paths. There is no override:\n"
            "a frozen path changes only by a human pushing to main.\n",
            file=sys.stderr,
        )
        for rel in offending:
            print(f"  {rel}", file=sys.stderr)
        return 1
    print("no frozen path in this diff")
    return 0


if __name__ == "__main__":
    sys.exit(main())
